### ISSUE TITLE
rozcestník v patičce

### ISSUE THREAD

**Issue by pemasat** [tachyon83/cooldance#9]

**Comment by pemasat** [comment]
z návrhu: http://jira.sutech.cz:8080/secure/attachment/10803/koncept4_uprava.jpg ten spodní přepínač
- popup na kontakt viz: http://jira.sutech.cz:8080/secure/attachment/10812/1920x1080_v4.jpg 
  poze s poli:
  e-mail + vzkaz

**Comment by fojmar** [comment]
Upraveno - popup jsem resil ciste pres jquery (prijde mi, ze to neni klasicky popup dialog)

**Comment by pemasat** [comment]
Bohužel se mi to nepodařilo zkomilovat, chybí přiložené definice pro
@social-width
@social-height
@social-border
@gray-dark
a možná i nějaké další. Můžeš prosím Marku překontrolovat?
Díky moc.

**Comment by fojmar** [comment]
zapomel jsem commit variables - docommitnuto

**Comment by pemasat** [comment]
Už je v pořádku. Díky moc.
